//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.SRM
{
    public partial class RegistrosSocios
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    		public static string ID = @"ID";
    public static string RegistroId = @"RegistroId";
    public static string SocioId = @"SocioId";
    public static string TipoSocio = @"TipoSocio";
    public static string TipoRelacion = @"TipoRelacion";
    public static string DireccionId = @"DireccionId";
    public static string RepresentanteId = @"RepresentanteId";
    public static string CargoId = @"CargoId";
    public static string NumeroRM = @"NumeroRM";
    public static string Orden = @"Orden";
    public static string FechaModificacion = @"FechaModificacion";
    public static string Deleted = @"Deleted";
    public static string CargoDescripcion = @"CargoDescripcion";
    public static string TipoRelacionDescripcion = @"TipoRelacionDescripcion";
    public static string CantidaCuotasAcciones = @"CantidaCuotasAcciones";
    public static string CodigoNominaSocio = @"CodigoNominaSocio";
    public static string VisibleEnCertificado = @"VisibleEnCertificado";
    public static string TipoBeneficiario = @"TipoBeneficiario";
    public static string IdentificacionTributariaPais = @"IdentificacionTributariaPais";
    public static string TipoDatosSocio = @"TipoDatosSocio";
    public static string CorreoElectronico = @"CorreoElectronico";
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int RegistroId
        {
            get;
            set;
        }
    
        public virtual int SocioId
        {
            get;
            set;
        }
    
        public virtual string TipoSocio
        {
            get;
            set;
        }
    
        public virtual string TipoRelacion
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DireccionId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> RepresentanteId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CargoId
        {
            get;
            set;
        }
    
        public virtual string NumeroRM
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Orden
        {
            get;
            set;
        }
    
        public virtual System.DateTime FechaModificacion
        {
            get;
            set;
        }
    
        public virtual System.Guid rowguid
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> Deleted
        {
            get;
            set;
        }
    
        public virtual string CargoDescripcion
        {
            get;
            set;
        }
    
        public virtual string TipoRelacionDescripcion
        {
            get;
            set;
        }
    
        public virtual decimal CantidaCuotasAcciones
        {
            get;
            set;
        }
    
        public virtual string CodigoNominaSocio
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> VisibleEnCertificado
        {
            get;
            set;
        }
    
        public virtual string TipoBeneficiario
        {
            get;
            set;
        }
    
        public virtual string IdentificacionTributariaPais
        {
            get;
            set;
        }
    
        public virtual string TipoDatosSocio
        {
            get;
            set;
        }
    
        public virtual string CorreoElectronico
        {
            get;
            set;
        }

        #endregion

    }
}
