//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.CamaraComun
{
    public partial class TipoSociedadCargos
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    			public static string TipoSociedadCargoId = @"TipoSociedadCargoId";	
    	public static string TipoSociedadId = @"TipoSociedadId";	
    	public static string CargoId = @"CargoId";	
    	public static string PuedeSerEmpresa = @"PuedeSerEmpresa";	
    	public static string CargoModificacion = @"CargoModificacion";	
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int TipoSociedadCargoId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TipoSociedadId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CargoId
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> PuedeSerEmpresa
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> CargoModificacion
        {
            get;
            set;
        }

        #endregion

    }
}
