//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.OficinaVirtual
{
    [Serializable]
    public partial class TempSocios
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    			public static string Id = @"Id";	
    	public static string TransaccionId = @"TransaccionId";	
    	public static string TipoSocio = @"TipoSocio";	
    	public static string TipoRelacion = @"TipoRelacion";	
    	public static string CargoId = @"CargoId";	
    	public static string TipoDocumento = @"TipoDocumento";	
    	public static string Documento = @"Documento";	
    	public static string NacionalidadId = @"NacionalidadId";	
    	public static string RegistroMercantil = @"RegistroMercantil";	
    	public static string Orden = @"Orden";	
    	public static string SociedadNombreSocial = @"SociedadNombreSocial";	
    	public static string PersonaPrimerNombre = @"PersonaPrimerNombre";	
    	public static string PersonaSegundoNombre = @"PersonaSegundoNombre";	
    	public static string PersonaPrimerApellido = @"PersonaPrimerApellido";	
    	public static string PersonaSegundoApellido = @"PersonaSegundoApellido";	
    	public static string PersonaEstadoCivil = @"PersonaEstadoCivil";	
    	public static string PersonaProfesionId = @"PersonaProfesionId";	
    	public static string DireccionCalle = @"DireccionCalle";	
    	public static string DireccionNumero = @"DireccionNumero";	
    	public static string DireccionCiudadId = @"DireccionCiudadId";	
    	public static string DireccionSectorId = @"DireccionSectorId";	
    	public static string DireccionApartadoPostal = @"DireccionApartadoPostal";	
    	public static string RepresentanteId = @"RepresentanteId";	
    	public static string CantidadAcciones = @"CantidadAcciones";	
    	public static string FechaNacimiento = @"FechaNacimiento";	
    	public static string TipoBeneficiario = @"TipoBeneficiario";	
    	public static string IdentificacionTributariaPais = @"IdentificacionTributariaPais";	
    	public static string TipoDatosSocio = @"TipoDatosSocio";	
    	public static string Telefono1 = @"Telefono1";	
    	public static string Telefono2 = @"Telefono2";	
    	public static string CorreoElectronico = @"CorreoElectronico";	
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int TransaccionId
        {
            get;
            set;
        }
    
        public virtual string TipoSocio
        {
            get;
            set;
        }
    
        public virtual string TipoRelacion
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CargoId
        {
            get;
            set;
        }
    
        public virtual string TipoDocumento
        {
            get;
            set;
        }
    
        public virtual string Documento
        {
            get;
            set;
        }
    
        public virtual Nullable<int> NacionalidadId
        {
            get;
            set;
        }
    
        public virtual string RegistroMercantil
        {
            get;
            set;
        }
    
        public virtual int Orden
        {
            get;
            set;
        }
    
        public virtual string SociedadNombreSocial
        {
            get;
            set;
        }
    
        public virtual string PersonaPrimerNombre
        {
            get;
            set;
        }
    
        public virtual string PersonaSegundoNombre
        {
            get;
            set;
        }
    
        public virtual string PersonaPrimerApellido
        {
            get;
            set;
        }
    
        public virtual string PersonaSegundoApellido
        {
            get;
            set;
        }
    
        public virtual string PersonaEstadoCivil
        {
            get;
            set;
        }
    
        public virtual Nullable<int> PersonaProfesionId
        {
            get;
            set;
        }
    
        public virtual string DireccionCalle
        {
            get;
            set;
        }
    
        public virtual string DireccionNumero
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DireccionCiudadId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DireccionSectorId
        {
            get;
            set;
        }
    
        public virtual string DireccionApartadoPostal
        {
            get;
            set;
        }
    
        public virtual Nullable<int> RepresentanteId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CantidadAcciones
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> FechaNacimiento
        {
            get;
            set;
        }
    
        public virtual string TipoBeneficiario
        {
            get;
            set;
        }
    
        public virtual string IdentificacionTributariaPais
        {
            get;
            set;
        }
    
        public virtual string TipoDatosSocio
        {
            get;
            set;
        }
    
        public virtual string Telefono1
        {
            get;
            set;
        }
    
        public virtual string Telefono2
        {
            get;
            set;
        }
    
        public virtual string CorreoElectronico
        {
            get;
            set;
        }

        #endregion

    }
}
