//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.OficinaVirtual
{
    [Serializable]
    public partial class TempActividadesTransaccion
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    			public static string AtividadId = @"AtividadId";	
    	public static string TransaccionId = @"TransaccionId";	
    	public static string TipoActividadId = @"TipoActividadId";	
    	public static string FechaModificacion = @"FechaModificacion";	
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int AtividadId
        {
            get;
            set;
        }
    
        public virtual int TransaccionId
        {
            get;
            set;
        }
    
        public virtual int TipoActividadId
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> FechaModificacion
        {
            get;
            set;
        }

        #endregion

    }
}
