//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.OficinaVirtual
{
    [Serializable]
    public partial class TransaccionCopiasCertificadas
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    			public static string Id = @"Id";	
    	public static string TransaccionId = @"TransaccionId";	
    	public static string Ruta = @"Ruta";	
    	public static string NombreDocumento = @"NombreDocumento";	
    	public static string FechaDocumento = @"FechaDocumento";	
    	public static string CantPaginas = @"CantPaginas";	
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int TransaccionId
        {
            get;
            set;
        }
    
        public virtual string Ruta
        {
            get;
            set;
        }
    
        public virtual string NombreDocumento
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> FechaDocumento
        {
            get;
            set;
        }
    
        public virtual int CantPaginas
        {
            get;
            set;
        }

        #endregion

    }
}
