//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.OficinaVirtual
{
    [Serializable]
    public partial class CategoriasSocios
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    			public static string TipoCategoriaId = @"TipoCategoriaId";	
    	public static string TipoCategoria = @"TipoCategoria";	
    	public static string Descripcion = @"Descripcion";	
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int TipoCategoriaId
        {
            get;
            set;
        }
    
        public virtual string TipoCategoria
        {
            get;
            set;
        }
    
        public virtual string Descripcion
        {
            get;
            set;
        }

        #endregion

    }
}
