//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.OficinaVirtual
{
    [Serializable]
    public partial class sysdiagrams
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    			public static string name = @"name";	
    	public static string principal_id = @"principal_id";	
    	public static string diagram_id = @"diagram_id";	
    	public static string version = @"version";	
    	public static string definition = @"definition";	
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual string name
        {
            get;
            set;
        }
    
        public virtual int principal_id
        {
            get;
            set;
        }
    
        public virtual int diagram_id
        {
            get;
            set;
        }
    
        public virtual Nullable<int> version
        {
            get;
            set;
        }
    
        public virtual byte[] definition
        {
            get;
            set;
        }

        #endregion

    }
}
