//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.OficinaVirtual
{
    [Serializable]
    public partial class TransaccionInfo
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    			public static string TransaccionId = @"TransaccionId";	
    	public static string FacturaPagadaId = @"FacturaPagadaId";	
    	public static string Problema = @"Problema";	
    	public static string CamaraId = @"CamaraId";	
    	public static string TransaccionIdAnterior = @"TransaccionIdAnterior";	
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int TransaccionId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> FacturaPagadaId
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> Problema
        {
            get;
            set;
        }
    
        public virtual string CamaraId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TransaccionIdAnterior
        {
            get;
            set;
        }

        #endregion

    }
}
