//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.SRM
{
    public partial class ViewRegistrosSocios
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    		public static string ID = @"ID";
    public static string RegistroId = @"RegistroId";
    public static string SocioId = @"SocioId";
    public static string TipoSocio = @"TipoSocio";
    public static string TipoRelacion = @"TipoRelacion";
    public static string DireccionId = @"DireccionId";
    public static string RalacionSocio = @"RalacionSocio";
    public static string RepresentanteId = @"RepresentanteId";
    public static string CargoId = @"CargoId";
    public static string NumeroRM = @"NumeroRM";
    public static string Orden = @"Orden";
    public static string FechaModificacion = @"FechaModificacion";
    public static string Documento = @"Documento";
    public static string Accionista = @"Accionista";
    public static string Representante = @"Representante";
    public static string Calle = @"Calle";
    public static string Numero = @"Numero";
    public static string CiudadId = @"CiudadId";
    public static string SectorId = @"SectorId";
    public static string ApartadoPostal = @"ApartadoPostal";
    public static string TelefonoCasa = @"TelefonoCasa";
    public static string TelefonoOficina = @"TelefonoOficina";
    public static string Extension = @"Extension";
    public static string Fax = @"Fax";
    public static string Email = @"Email";
    public static string SitioWeb = @"SitioWeb";
    public static string Ciudad = @"Ciudad";
    public static string Sector = @"Sector";
    public static string Pais = @"Pais";
    public static string Cargo = @"Cargo";
    public static string Nacionalidad = @"Nacionalidad";
    public static string Profesion = @"Profesion";
    public static string EstadoCivil = @"EstadoCivil";
    public static string CantidaCuotasAcciones = @"CantidaCuotasAcciones";
    public static string CargoDescripcion = @"CargoDescripcion";
    public static string SectorDgiiId = @"SectorDgiiId";
    public static string SectorDgii = @"SectorDgii";
    public static string PaisId = @"PaisId";
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int RegistroId
        {
            get;
            set;
        }
    
        public virtual int SocioId
        {
            get;
            set;
        }
    
        public virtual string TipoSocio
        {
            get;
            set;
        }
    
        public virtual string TipoRelacion
        {
            get;
            set;
        }
    
        public virtual Nullable<int> DireccionId
        {
            get;
            set;
        }
    
        public virtual string RalacionSocio
        {
            get;
            set;
        }
    
        public virtual Nullable<int> RepresentanteId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CargoId
        {
            get;
            set;
        }
    
        public virtual string NumeroRM
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Orden
        {
            get;
            set;
        }
    
        public virtual System.DateTime FechaModificacion
        {
            get;
            set;
        }
    
        public virtual System.Guid rowguid
        {
            get;
            set;
        }
    
        public virtual string Documento
        {
            get;
            set;
        }
    
        public virtual string Accionista
        {
            get;
            set;
        }
    
        public virtual string Representante
        {
            get;
            set;
        }
    
        public virtual string Calle
        {
            get;
            set;
        }
    
        public virtual string Numero
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CiudadId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SectorId
        {
            get;
            set;
        }
    
        public virtual string ApartadoPostal
        {
            get;
            set;
        }
    
        public virtual string TelefonoCasa
        {
            get;
            set;
        }
    
        public virtual string TelefonoOficina
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Extension
        {
            get;
            set;
        }
    
        public virtual string Fax
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
        public virtual string SitioWeb
        {
            get;
            set;
        }
    
        public virtual string Ciudad
        {
            get;
            set;
        }
    
        public virtual string Sector
        {
            get;
            set;
        }
    
        public virtual string Pais
        {
            get;
            set;
        }
    
        public virtual string Cargo
        {
            get;
            set;
        }
    
        public virtual string Nacionalidad
        {
            get;
            set;
        }
    
        public virtual string Profesion
        {
            get;
            set;
        }
    
        public virtual string EstadoCivil
        {
            get;
            set;
        }
    
        public virtual decimal CantidaCuotasAcciones
        {
            get;
            set;
        }
    
        public virtual string CargoDescripcion
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SectorDgiiId
        {
            get;
            set;
        }
    
        public virtual string SectorDgii
        {
            get;
            set;
        }
    
        public virtual Nullable<int> PaisId
        {
            get;
            set;
        }

        #endregion

    }
}
