//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.SRM
{
    public partial class UbicacionesExpedientes
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    		public static string Id = @"Id";
    public static string Descripcion = @"Descripcion";
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Descripcion
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<Transacciones> Transacciones
        {
            get
            {
                if (_transacciones == null)
                {
                    var newCollection = new FixupCollection<Transacciones>();
                    newCollection.CollectionChanged += FixupTransacciones;
                    _transacciones = newCollection;
                }
                return _transacciones;
            }
            set
            {
                if (!ReferenceEquals(_transacciones, value))
                {
                    var previousValue = _transacciones as FixupCollection<Transacciones>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTransacciones;
                    }
                    _transacciones = value;
                    var newValue = value as FixupCollection<Transacciones>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTransacciones;
                    }
                }
            }
        }
        private ICollection<Transacciones> _transacciones;

        #endregion

        #region Association Fixup
    
        private void FixupTransacciones(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Transacciones item in e.NewItems)
                {
                    item.UbicacionesExpedientes = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Transacciones item in e.OldItems)
                {
                    if (ReferenceEquals(item.UbicacionesExpedientes, this))
                    {
                        item.UbicacionesExpedientes = null;
                    }
                }
            }
        }

        #endregion

    }
}
