//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.OficinaVirtual
{
    [Serializable]
    public partial class DatosGenerales
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    			public static string Id = @"Id";	
    	public static string TransaccionId = @"TransaccionId";	
    	public static string Calle = @"Calle";	
    	public static string CalleNumero = @"CalleNumero";	
    	public static string CiudadId = @"CiudadId";	
    	public static string Ciudad = @"Ciudad";	
    	public static string SectorId = @"SectorId";	
    	public static string SectorDescripcion = @"SectorDescripcion";	
    	public static string ApartadoPostal = @"ApartadoPostal";	
    	public static string Telefono1 = @"Telefono1";	
    	public static string Telefono2 = @"Telefono2";	
    	public static string Fax = @"Fax";	
    	public static string Email = @"Email";	
    	public static string WebSite = @"WebSite";	
    	public static string ActividadCIUU1 = @"ActividadCIUU1";	
    	public static string ActividadCIUU1Desc = @"ActividadCIUU1Desc";	
    	public static string ActividadCIUU2 = @"ActividadCIUU2";	
    	public static string ActividadCIUU2Desc = @"ActividadCIUU2Desc";	
    	public static string ObjetoEmpresa = @"ObjetoEmpresa";	
    	public static string Usuario = @"Usuario";	
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TransaccionId
        {
            get;
            set;
        }
    
        public virtual string Calle
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CalleNumero
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CiudadId
        {
            get;
            set;
        }
    
        public virtual string Ciudad
        {
            get;
            set;
        }
    
        public virtual Nullable<int> SectorId
        {
            get;
            set;
        }
    
        public virtual string SectorDescripcion
        {
            get;
            set;
        }
    
        public virtual string ApartadoPostal
        {
            get;
            set;
        }
    
        public virtual string Telefono1
        {
            get;
            set;
        }
    
        public virtual string Telefono2
        {
            get;
            set;
        }
    
        public virtual string Fax
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }
    
        public virtual string WebSite
        {
            get;
            set;
        }
    
        public virtual string ActividadCIUU1
        {
            get;
            set;
        }
    
        public virtual string ActividadCIUU1Desc
        {
            get;
            set;
        }
    
        public virtual string ActividadCIUU2
        {
            get;
            set;
        }
    
        public virtual string ActividadCIUU2Desc
        {
            get;
            set;
        }
    
        public virtual string ObjetoEmpresa
        {
            get;
            set;
        }
    
        public virtual string Usuario
        {
            get;
            set;
        }

        #endregion

    }
}
