//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CamaraComercio.Website.svrkofax {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsCSISoap", Namespace="http://tempuri.org/")]
    public partial class wsCSI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getPathOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPathFulltextSearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPathCamaraOnlineOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsCSI() {
            this.Url = global::CamaraComercio.Website.Properties.Settings.Default.CamaraComercio_Website_svrkofax_wsCSI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getPathCompletedEventHandler getPathCompleted;
        
        /// <remarks/>
        public event getPathFulltextSearchCompletedEventHandler getPathFulltextSearchCompleted;
        
        /// <remarks/>
        public event getPathCamaraOnlineCompletedEventHandler getPathCamaraOnlineCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPath", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getPath(int paramTipoBusqueda, string id) {
            object[] results = this.Invoke("getPath", new object[] {
                        paramTipoBusqueda,
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getPathAsync(int paramTipoBusqueda, string id) {
            this.getPathAsync(paramTipoBusqueda, id, null);
        }
        
        /// <remarks/>
        public void getPathAsync(int paramTipoBusqueda, string id, object userState) {
            if ((this.getPathOperationCompleted == null)) {
                this.getPathOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPathOperationCompleted);
            }
            this.InvokeAsync("getPath", new object[] {
                        paramTipoBusqueda,
                        id}, this.getPathOperationCompleted, userState);
        }
        
        private void OngetPathOperationCompleted(object arg) {
            if ((this.getPathCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPathCompleted(this, new getPathCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPathFulltextSearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getPathFulltextSearch(int paramTipoBusqueda, string id, string fulltextSearch) {
            object[] results = this.Invoke("getPathFulltextSearch", new object[] {
                        paramTipoBusqueda,
                        id,
                        fulltextSearch});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getPathFulltextSearchAsync(int paramTipoBusqueda, string id, string fulltextSearch) {
            this.getPathFulltextSearchAsync(paramTipoBusqueda, id, fulltextSearch, null);
        }
        
        /// <remarks/>
        public void getPathFulltextSearchAsync(int paramTipoBusqueda, string id, string fulltextSearch, object userState) {
            if ((this.getPathFulltextSearchOperationCompleted == null)) {
                this.getPathFulltextSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPathFulltextSearchOperationCompleted);
            }
            this.InvokeAsync("getPathFulltextSearch", new object[] {
                        paramTipoBusqueda,
                        id,
                        fulltextSearch}, this.getPathFulltextSearchOperationCompleted, userState);
        }
        
        private void OngetPathFulltextSearchOperationCompleted(object arg) {
            if ((this.getPathFulltextSearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPathFulltextSearchCompleted(this, new getPathFulltextSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getPathCamaraOnline", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getPathCamaraOnline(int paramTipoBusqueda, string id) {
            object[] results = this.Invoke("getPathCamaraOnline", new object[] {
                        paramTipoBusqueda,
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getPathCamaraOnlineAsync(int paramTipoBusqueda, string id) {
            this.getPathCamaraOnlineAsync(paramTipoBusqueda, id, null);
        }
        
        /// <remarks/>
        public void getPathCamaraOnlineAsync(int paramTipoBusqueda, string id, object userState) {
            if ((this.getPathCamaraOnlineOperationCompleted == null)) {
                this.getPathCamaraOnlineOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPathCamaraOnlineOperationCompleted);
            }
            this.InvokeAsync("getPathCamaraOnline", new object[] {
                        paramTipoBusqueda,
                        id}, this.getPathCamaraOnlineOperationCompleted, userState);
        }
        
        private void OngetPathCamaraOnlineOperationCompleted(object arg) {
            if ((this.getPathCamaraOnlineCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPathCamaraOnlineCompleted(this, new getPathCamaraOnlineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getPathCompletedEventHandler(object sender, getPathCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getPathFulltextSearchCompletedEventHandler(object sender, getPathFulltextSearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPathFulltextSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPathFulltextSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getPathCamaraOnlineCompletedEventHandler(object sender, getPathCamaraOnlineCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPathCamaraOnlineCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPathCamaraOnlineCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591