//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CamaraComercio.Website.wsReporteRM {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsRegistroMercantilSoap", Namespace="http://tempuri.org/")]
    public partial class wsRegistroMercantil : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuscarSocio_RMOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarSocio_DocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarRMOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListaCamarasActivasOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLogConsultaIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback VerCertificadoRMOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsRegistroMercantil() {
            this.Url = global::CamaraComercio.Website.Properties.Settings.Default.CamaraComercio_Website_wsReporteRM_wsRegistroMercantil;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuscarSocio_RMCompletedEventHandler BuscarSocio_RMCompleted;
        
        /// <remarks/>
        public event BuscarSocio_DocumentoCompletedEventHandler BuscarSocio_DocumentoCompleted;
        
        /// <remarks/>
        public event BuscarRMCompletedEventHandler BuscarRMCompleted;
        
        /// <remarks/>
        public event ListaCamarasActivasCompletedEventHandler ListaCamarasActivasCompleted;
        
        /// <remarks/>
        public event GetLogConsultaIdCompletedEventHandler GetLogConsultaIdCompleted;
        
        /// <remarks/>
        public event VerCertificadoRMCompletedEventHandler VerCertificadoRMCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarSocio_RM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Accionista[] BuscarSocio_RM(string userName, string password, string camaraId, int tipoRegistro, int noRegistro) {
            object[] results = this.Invoke("BuscarSocio_RM", new object[] {
                        userName,
                        password,
                        camaraId,
                        tipoRegistro,
                        noRegistro});
            return ((Accionista[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarSocio_RMAsync(string userName, string password, string camaraId, int tipoRegistro, int noRegistro) {
            this.BuscarSocio_RMAsync(userName, password, camaraId, tipoRegistro, noRegistro, null);
        }
        
        /// <remarks/>
        public void BuscarSocio_RMAsync(string userName, string password, string camaraId, int tipoRegistro, int noRegistro, object userState) {
            if ((this.BuscarSocio_RMOperationCompleted == null)) {
                this.BuscarSocio_RMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarSocio_RMOperationCompleted);
            }
            this.InvokeAsync("BuscarSocio_RM", new object[] {
                        userName,
                        password,
                        camaraId,
                        tipoRegistro,
                        noRegistro}, this.BuscarSocio_RMOperationCompleted, userState);
        }
        
        private void OnBuscarSocio_RMOperationCompleted(object arg) {
            if ((this.BuscarSocio_RMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarSocio_RMCompleted(this, new BuscarSocio_RMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarSocio_Documento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Accionista[] BuscarSocio_Documento(string userName, string password, string camaraId, int tipoRegistro, int noRegistro, string documento) {
            object[] results = this.Invoke("BuscarSocio_Documento", new object[] {
                        userName,
                        password,
                        camaraId,
                        tipoRegistro,
                        noRegistro,
                        documento});
            return ((Accionista[])(results[0]));
        }
        
        /// <remarks/>
        public void BuscarSocio_DocumentoAsync(string userName, string password, string camaraId, int tipoRegistro, int noRegistro, string documento) {
            this.BuscarSocio_DocumentoAsync(userName, password, camaraId, tipoRegistro, noRegistro, documento, null);
        }
        
        /// <remarks/>
        public void BuscarSocio_DocumentoAsync(string userName, string password, string camaraId, int tipoRegistro, int noRegistro, string documento, object userState) {
            if ((this.BuscarSocio_DocumentoOperationCompleted == null)) {
                this.BuscarSocio_DocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarSocio_DocumentoOperationCompleted);
            }
            this.InvokeAsync("BuscarSocio_Documento", new object[] {
                        userName,
                        password,
                        camaraId,
                        tipoRegistro,
                        noRegistro,
                        documento}, this.BuscarSocio_DocumentoOperationCompleted, userState);
        }
        
        private void OnBuscarSocio_DocumentoOperationCompleted(object arg) {
            if ((this.BuscarSocio_DocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarSocio_DocumentoCompleted(this, new BuscarSocio_DocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarRM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Registro BuscarRM(string userName, string password, string camaraId, int tipoRegistro, int noRegistro) {
            object[] results = this.Invoke("BuscarRM", new object[] {
                        userName,
                        password,
                        camaraId,
                        tipoRegistro,
                        noRegistro});
            return ((Registro)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarRMAsync(string userName, string password, string camaraId, int tipoRegistro, int noRegistro) {
            this.BuscarRMAsync(userName, password, camaraId, tipoRegistro, noRegistro, null);
        }
        
        /// <remarks/>
        public void BuscarRMAsync(string userName, string password, string camaraId, int tipoRegistro, int noRegistro, object userState) {
            if ((this.BuscarRMOperationCompleted == null)) {
                this.BuscarRMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarRMOperationCompleted);
            }
            this.InvokeAsync("BuscarRM", new object[] {
                        userName,
                        password,
                        camaraId,
                        tipoRegistro,
                        noRegistro}, this.BuscarRMOperationCompleted, userState);
        }
        
        private void OnBuscarRMOperationCompleted(object arg) {
            if ((this.BuscarRMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarRMCompleted(this, new BuscarRMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListaCamarasActivas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Camara[] ListaCamarasActivas(string userName, string password) {
            object[] results = this.Invoke("ListaCamarasActivas", new object[] {
                        userName,
                        password});
            return ((Camara[])(results[0]));
        }
        
        /// <remarks/>
        public void ListaCamarasActivasAsync(string userName, string password) {
            this.ListaCamarasActivasAsync(userName, password, null);
        }
        
        /// <remarks/>
        public void ListaCamarasActivasAsync(string userName, string password, object userState) {
            if ((this.ListaCamarasActivasOperationCompleted == null)) {
                this.ListaCamarasActivasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListaCamarasActivasOperationCompleted);
            }
            this.InvokeAsync("ListaCamarasActivas", new object[] {
                        userName,
                        password}, this.ListaCamarasActivasOperationCompleted, userState);
        }
        
        private void OnListaCamarasActivasOperationCompleted(object arg) {
            if ((this.ListaCamarasActivasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListaCamarasActivasCompleted(this, new ListaCamarasActivasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLogConsultaId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLogConsultaId(string userName, string password, int consultaId) {
            object[] results = this.Invoke("GetLogConsultaId", new object[] {
                        userName,
                        password,
                        consultaId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLogConsultaIdAsync(string userName, string password, int consultaId) {
            this.GetLogConsultaIdAsync(userName, password, consultaId, null);
        }
        
        /// <remarks/>
        public void GetLogConsultaIdAsync(string userName, string password, int consultaId, object userState) {
            if ((this.GetLogConsultaIdOperationCompleted == null)) {
                this.GetLogConsultaIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLogConsultaIdOperationCompleted);
            }
            this.InvokeAsync("GetLogConsultaId", new object[] {
                        userName,
                        password,
                        consultaId}, this.GetLogConsultaIdOperationCompleted, userState);
        }
        
        private void OnGetLogConsultaIdOperationCompleted(object arg) {
            if ((this.GetLogConsultaIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLogConsultaIdCompleted(this, new GetLogConsultaIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/VerCertificadoRM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VerCertificadoRM(string userName, string password, int NumeroRM, int TipoSociedad, string CamaraId) {
            object[] results = this.Invoke("VerCertificadoRM", new object[] {
                        userName,
                        password,
                        NumeroRM,
                        TipoSociedad,
                        CamaraId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VerCertificadoRMAsync(string userName, string password, int NumeroRM, int TipoSociedad, string CamaraId) {
            this.VerCertificadoRMAsync(userName, password, NumeroRM, TipoSociedad, CamaraId, null);
        }
        
        /// <remarks/>
        public void VerCertificadoRMAsync(string userName, string password, int NumeroRM, int TipoSociedad, string CamaraId, object userState) {
            if ((this.VerCertificadoRMOperationCompleted == null)) {
                this.VerCertificadoRMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVerCertificadoRMOperationCompleted);
            }
            this.InvokeAsync("VerCertificadoRM", new object[] {
                        userName,
                        password,
                        NumeroRM,
                        TipoSociedad,
                        CamaraId}, this.VerCertificadoRMOperationCompleted, userState);
        }
        
        private void OnVerCertificadoRMOperationCompleted(object arg) {
            if ((this.VerCertificadoRMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VerCertificadoRMCompleted(this, new VerCertificadoRMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Accionista {
        
        private string documentoField;
        
        private string nombreAccionistaField;
        
        private string cargoField;
        
        private string relacionField;
        
        private string camaraIdField;
        
        private int tipoRegistroField;
        
        private string noRegistroField;
        
        private string nombreEmpresaField;
        
        private decimal cantidadAccionesField;
        
        private int idConsultaField;
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public string NombreAccionista {
            get {
                return this.nombreAccionistaField;
            }
            set {
                this.nombreAccionistaField = value;
            }
        }
        
        /// <remarks/>
        public string Cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
            }
        }
        
        /// <remarks/>
        public string Relacion {
            get {
                return this.relacionField;
            }
            set {
                this.relacionField = value;
            }
        }
        
        /// <remarks/>
        public string CamaraId {
            get {
                return this.camaraIdField;
            }
            set {
                this.camaraIdField = value;
            }
        }
        
        /// <remarks/>
        public int TipoRegistro {
            get {
                return this.tipoRegistroField;
            }
            set {
                this.tipoRegistroField = value;
            }
        }
        
        /// <remarks/>
        public string NoRegistro {
            get {
                return this.noRegistroField;
            }
            set {
                this.noRegistroField = value;
            }
        }
        
        /// <remarks/>
        public string NombreEmpresa {
            get {
                return this.nombreEmpresaField;
            }
            set {
                this.nombreEmpresaField = value;
            }
        }
        
        /// <remarks/>
        public decimal CantidadAcciones {
            get {
                return this.cantidadAccionesField;
            }
            set {
                this.cantidadAccionesField = value;
            }
        }
        
        /// <remarks/>
        public int IdConsulta {
            get {
                return this.idConsultaField;
            }
            set {
                this.idConsultaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Camara {
        
        private string codigoField;
        
        private string nombreField;
        
        private string nombreCompletoField;
        
        private bool activaField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public string NombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
            }
        }
        
        /// <remarks/>
        public bool Activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Registro {
        
        private string camaraIdField;
        
        private string denominacionSocialField;
        
        private string nombreComercialField;
        
        private int tipoRegistroField;
        
        private int registroMercantilField;
        
        private string dirTelefono1Field;
        
        private string dirTelefono2Field;
        
        private string dirFaxField;
        
        private string dirEmailField;
        
        private string rNCField;
        
        private System.DateTime fechaFormacionField;
        
        private System.DateTime fechaEmisionRMField;
        
        private System.DateTime fechaVencimientoRMField;
        
        private bool estatusField;
        
        private decimal capitalSocialField;
        
        private string nacionalidadField;
        
        private int empleadosMasculinosField;
        
        private int empleadosFemeninosField;
        
        private int empleadosTotalField;
        
        private string actividadNegocioField;
        
        private int idConsultaField;
        
        /// <remarks/>
        public string CamaraId {
            get {
                return this.camaraIdField;
            }
            set {
                this.camaraIdField = value;
            }
        }
        
        /// <remarks/>
        public string DenominacionSocial {
            get {
                return this.denominacionSocialField;
            }
            set {
                this.denominacionSocialField = value;
            }
        }
        
        /// <remarks/>
        public string NombreComercial {
            get {
                return this.nombreComercialField;
            }
            set {
                this.nombreComercialField = value;
            }
        }
        
        /// <remarks/>
        public int TipoRegistro {
            get {
                return this.tipoRegistroField;
            }
            set {
                this.tipoRegistroField = value;
            }
        }
        
        /// <remarks/>
        public int RegistroMercantil {
            get {
                return this.registroMercantilField;
            }
            set {
                this.registroMercantilField = value;
            }
        }
        
        /// <remarks/>
        public string DirTelefono1 {
            get {
                return this.dirTelefono1Field;
            }
            set {
                this.dirTelefono1Field = value;
            }
        }
        
        /// <remarks/>
        public string DirTelefono2 {
            get {
                return this.dirTelefono2Field;
            }
            set {
                this.dirTelefono2Field = value;
            }
        }
        
        /// <remarks/>
        public string DirFax {
            get {
                return this.dirFaxField;
            }
            set {
                this.dirFaxField = value;
            }
        }
        
        /// <remarks/>
        public string DirEmail {
            get {
                return this.dirEmailField;
            }
            set {
                this.dirEmailField = value;
            }
        }
        
        /// <remarks/>
        public string RNC {
            get {
                return this.rNCField;
            }
            set {
                this.rNCField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaFormacion {
            get {
                return this.fechaFormacionField;
            }
            set {
                this.fechaFormacionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaEmisionRM {
            get {
                return this.fechaEmisionRMField;
            }
            set {
                this.fechaEmisionRMField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaVencimientoRM {
            get {
                return this.fechaVencimientoRMField;
            }
            set {
                this.fechaVencimientoRMField = value;
            }
        }
        
        /// <remarks/>
        public bool Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        public decimal CapitalSocial {
            get {
                return this.capitalSocialField;
            }
            set {
                this.capitalSocialField = value;
            }
        }
        
        /// <remarks/>
        public string Nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
            }
        }
        
        /// <remarks/>
        public int EmpleadosMasculinos {
            get {
                return this.empleadosMasculinosField;
            }
            set {
                this.empleadosMasculinosField = value;
            }
        }
        
        /// <remarks/>
        public int EmpleadosFemeninos {
            get {
                return this.empleadosFemeninosField;
            }
            set {
                this.empleadosFemeninosField = value;
            }
        }
        
        /// <remarks/>
        public int EmpleadosTotal {
            get {
                return this.empleadosTotalField;
            }
            set {
                this.empleadosTotalField = value;
            }
        }
        
        /// <remarks/>
        public string ActividadNegocio {
            get {
                return this.actividadNegocioField;
            }
            set {
                this.actividadNegocioField = value;
            }
        }
        
        /// <remarks/>
        public int IdConsulta {
            get {
                return this.idConsultaField;
            }
            set {
                this.idConsultaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BuscarSocio_RMCompletedEventHandler(object sender, BuscarSocio_RMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarSocio_RMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarSocio_RMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Accionista[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Accionista[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BuscarSocio_DocumentoCompletedEventHandler(object sender, BuscarSocio_DocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarSocio_DocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarSocio_DocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Accionista[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Accionista[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BuscarRMCompletedEventHandler(object sender, BuscarRMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarRMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarRMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Registro Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Registro)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ListaCamarasActivasCompletedEventHandler(object sender, ListaCamarasActivasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListaCamarasActivasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListaCamarasActivasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Camara[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Camara[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetLogConsultaIdCompletedEventHandler(object sender, GetLogConsultaIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLogConsultaIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLogConsultaIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void VerCertificadoRMCompletedEventHandler(object sender, VerCertificadoRMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VerCertificadoRMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VerCertificadoRMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591