//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.CamaraComun
{
    public partial class TiposNcf
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    			public static string TipoNcfId = @"TipoNcfId";	
    	public static string Descripcion = @"Descripcion";	
    	public static string SiteVisible = @"SiteVisible";	
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int TipoNcfId
        {
            get;
            set;
        }
    
        public virtual string Descripcion
        {
            get;
            set;
        }
    
        public virtual bool SiteVisible
        {
            get;
            set;
        }

        #endregion

    }
}
