//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.Membership
{
    public partial class vw_aspnet_Roles
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    		public static string ApplicationId = @"ApplicationId";
    public static string RoleId = @"RoleId";
    public static string RoleName = @"RoleName";
    public static string LoweredRoleName = @"LoweredRoleName";
    public static string Description = @"Description";
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual System.Guid ApplicationId
        {
            get;
            set;
        }
    
        public virtual System.Guid RoleId
        {
            get;
            set;
        }
    
        public virtual string RoleName
        {
            get;
            set;
        }
    
        public virtual string LoweredRoleName
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }

        #endregion

    }
}
