//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.Membership
{
    public partial class site_Themes
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    		public static string ThemeId = @"ThemeId";
    public static string ThemeUrl = @"ThemeUrl";
    public static string ThemeThumbUrl = @"ThemeThumbUrl";
    public static string ThemeName = @"ThemeName";
    public static string ThemeDescription = @"ThemeDescription";
    public static string ThemeCategory = @"ThemeCategory";
    public static string IsEnabled = @"IsEnabled";
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int ThemeId
        {
            get;
            set;
        }
    
        public virtual string ThemeUrl
        {
            get;
            set;
        }
    
        public virtual string ThemeThumbUrl
        {
            get;
            set;
        }
    
        public virtual string ThemeName
        {
            get;
            set;
        }
    
        public virtual string ThemeDescription
        {
            get;
            set;
        }
    
        public virtual string ThemeCategory
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsEnabled
        {
            get;
            set;
        }

        #endregion

    }
}
