//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.SRM
{
    public partial class Tarifas
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    		public static string TarifaId = @"TarifaId";
    public static string Descripcion = @"Descripcion";
    public static string MontoInicial = @"MontoInicial";
    public static string MontoFinal = @"MontoFinal";
    public static string CostoContitucion = @"CostoContitucion";
    public static string CostoModificacion = @"CostoModificacion";
    public static string CostoModificacionNeto = @"CostoModificacionNeto";
    public static string CostoRenovacion = @"CostoRenovacion";
    public static string CostoRenovacionNeto = @"CostoRenovacionNeto";
    public static string CostoContitucionVU = @"CostoContitucionVU";
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int TarifaId
        {
            get;
            set;
        }
    
        public virtual string Descripcion
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> MontoInicial
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> MontoFinal
        {
            get;
            set;
        }
    
        public virtual decimal CostoContitucion
        {
            get;
            set;
        }
    
        public virtual decimal CostoModificacion
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> CostoModificacionNeto
        {
            get;
            set;
        }
    
        public virtual decimal CostoRenovacion
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> CostoRenovacionNeto
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> CostoContitucionVU
        {
            get;
            set;
        }

        #endregion

    }
}
