//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.SRM
{
    public partial class TransaccionDetalle
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    		public static string TransaccionDetalles = @"TransaccionDetalles";
    public static string FacturaId = @"FacturaId";
    public static string Cuenta = @"Cuenta";
    public static string Detalle = @"Detalle";
    public static string Cantidad = @"Cantidad";
    public static string PrecioUnitario = @"PrecioUnitario";
    public static string Descuento = @"Descuento";
    public static string Total = @"Total";
    public static string TotalBruto = @"TotalBruto";
    public static string ServicioId = @"ServicioId";
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int TransaccionDetalles
        {
            get;
            set;
        }
    
        public virtual int FacturaId
        {
            get { return _facturaId; }
            set
            {
                if (_facturaId != value)
                {
                    if (Facturas != null && Facturas.FacturaId != value)
                    {
                        Facturas = null;
                    }
                    _facturaId = value;
                }
            }
        }
        private int _facturaId;
    
        public virtual string Cuenta
        {
            get;
            set;
        }
    
        public virtual string Detalle
        {
            get;
            set;
        }
    
        public virtual int Cantidad
        {
            get;
            set;
        }
    
        public virtual decimal PrecioUnitario
        {
            get;
            set;
        }
    
        public virtual decimal Descuento
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Total
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> TotalBruto
        {
            get;
            set;
        }
    
        public virtual int ServicioId
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Facturas Facturas
        {
            get { return _facturas; }
            set
            {
                if (!ReferenceEquals(_facturas, value))
                {
                    var previousValue = _facturas;
                    _facturas = value;
                    FixupFacturas(previousValue);
                }
            }
        }
        private Facturas _facturas;

        #endregion

        #region Association Fixup
    
        private void FixupFacturas(Facturas previousValue)
        {
            if (previousValue != null && previousValue.TransaccionDetalle.Contains(this))
            {
                previousValue.TransaccionDetalle.Remove(this);
            }
    
            if (Facturas != null)
            {
                if (!Facturas.TransaccionDetalle.Contains(this))
                {
                    Facturas.TransaccionDetalle.Add(this);
                }
                if (FacturaId != Facturas.FacturaId)
                {
                    FacturaId = Facturas.FacturaId;
                }
            }
        }

        #endregion

    }
}
