//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.SRM
{
    public partial class SociedadesLogos
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    		public static string SociedadLogoId = @"SociedadLogoId";
    public static string SociedadId = @"SociedadId";
    public static string Logo = @"Logo";
    public static string LogoSmall = @"LogoSmall";
    public static string FechaCreacion = @"FechaCreacion";
    public static string Extension = @"Extension";
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int SociedadLogoId
        {
            get;
            set;
        }
    
        public virtual int SociedadId
        {
            get { return _sociedadId; }
            set
            {
                if (_sociedadId != value)
                {
                    if (Sociedades != null && Sociedades.SociedadId != value)
                    {
                        Sociedades = null;
                    }
                    _sociedadId = value;
                }
            }
        }
        private int _sociedadId;
    
        public virtual byte[] Logo
        {
            get;
            set;
        }
    
        public virtual byte[] LogoSmall
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> FechaCreacion
        {
            get;
            set;
        }
    
        public virtual string Extension
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Sociedades Sociedades
        {
            get { return _sociedades; }
            set
            {
                if (!ReferenceEquals(_sociedades, value))
                {
                    var previousValue = _sociedades;
                    _sociedades = value;
                    FixupSociedades(previousValue);
                }
            }
        }
        private Sociedades _sociedades;

        #endregion

        #region Association Fixup
    
        private void FixupSociedades(Sociedades previousValue)
        {
            if (previousValue != null && previousValue.SociedadesLogos.Contains(this))
            {
                previousValue.SociedadesLogos.Remove(this);
            }
    
            if (Sociedades != null)
            {
                if (!Sociedades.SociedadesLogos.Contains(this))
                {
                    Sociedades.SociedadesLogos.Add(this);
                }
                if (SociedadId != Sociedades.SociedadId)
                {
                    SociedadId = Sociedades.SociedadId;
                }
            }
        }

        #endregion

    }
}
