//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.SRM
{
    public partial class Modulos
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    		public static string ModuloId = @"ModuloId";
    public static string ModuloPadreId = @"ModuloPadreId";
    public static string Nombre = @"Nombre";
    public static string NombreEtiqueta = @"NombreEtiqueta";
    public static string Tag = @"Tag";
    public static string Orden = @"Orden";
    public static string CreateSerparator = @"CreateSerparator";
    public static string Icon = @"Icon";
    public static string ShowInNavBar = @"ShowInNavBar";
    public static string ShowInTreeNavBar = @"ShowInTreeNavBar";
    public static string SoloAdministrador = @"SoloAdministrador";
    public static string HeredaPadre = @"HeredaPadre";
    public static string HiddenOption = @"HiddenOption";
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int ModuloId
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ModuloPadreId
        {
            get;
            set;
        }
    
        public virtual string Nombre
        {
            get;
            set;
        }
    
        public virtual string NombreEtiqueta
        {
            get;
            set;
        }
    
        public virtual string Tag
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Orden
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> CreateSerparator
        {
            get;
            set;
        }
    
        public virtual byte[] Icon
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> ShowInNavBar
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> ShowInTreeNavBar
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> SoloAdministrador
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> HeredaPadre
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> HiddenOption
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<ModulosRoles> ModulosRoles
        {
            get
            {
                if (_modulosRoles == null)
                {
                    var newCollection = new FixupCollection<ModulosRoles>();
                    newCollection.CollectionChanged += FixupModulosRoles;
                    _modulosRoles = newCollection;
                }
                return _modulosRoles;
            }
            set
            {
                if (!ReferenceEquals(_modulosRoles, value))
                {
                    var previousValue = _modulosRoles as FixupCollection<ModulosRoles>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupModulosRoles;
                    }
                    _modulosRoles = value;
                    var newValue = value as FixupCollection<ModulosRoles>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupModulosRoles;
                    }
                }
            }
        }
        private ICollection<ModulosRoles> _modulosRoles;

        #endregion

        #region Association Fixup
    
        private void FixupModulosRoles(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ModulosRoles item in e.NewItems)
                {
                    item.Modulos = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ModulosRoles item in e.OldItems)
                {
                    if (ReferenceEquals(item.Modulos, this))
                    {
                        item.Modulos = null;
                    }
                }
            }
        }

        #endregion

    }
}
