//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.SRM
{
    public partial class ViewRegistrosProductos
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    		public static string ProductoId = @"ProductoId";
    public static string RegistroId = @"RegistroId";
    public static string Descripcion = @"Descripcion";
    public static string FechaModificacion = @"FechaModificacion";
    public static string SistemaArmonizadoId = @"SistemaArmonizadoId";
    public static string SistemaAmortizado = @"SistemaAmortizado";
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int ProductoId
        {
            get;
            set;
        }
    
        public virtual int RegistroId
        {
            get;
            set;
        }
    
        public virtual string Descripcion
        {
            get;
            set;
        }
    
        public virtual System.DateTime FechaModificacion
        {
            get;
            set;
        }
    
        public virtual System.Guid rowguid
        {
            get;
            set;
        }
    
        public virtual string SistemaArmonizadoId
        {
            get;
            set;
        }
    
        public virtual string SistemaAmortizado
        {
            get;
            set;
        }

        #endregion

    }
}
