CREATE TABLE [WebSRM].[Registros]
(
[RegistroId] [int] NOT NULL IDENTITY(1, 1),
[RegistroMercantil] [int] NULL,
[FechaEmision] [datetime] NULL,
[FechaVencimiento] [datetime] NULL,
[CapitalSocial] [money] NULL,
[CapitalAutorizado] [money] NULL,
[CapitalPagado] [money] NULL,
[Activos] [money] NULL,
[BienesRaices] [money] NULL,
[FechaInicioOperacion] [datetime] NULL,
[EmpleadosMasculinos] [int] NULL CONSTRAINT [DF_Registros_EmpleadosMasculinos] DEFAULT ((0)),
[EmpleadosFemeninos] [int] NULL CONSTRAINT [DF_Registros_EmpleadosFemeninos] DEFAULT ((0)),
[EmpleadosTotal] AS ([EmpleadosMasculinos]+[EmpleadosFemeninos]),
[NombreComercial] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegistroNombreComercial] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MarcaFabrica] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegistroMarcaFabrica] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PatenteInvencion] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RegistroPatenteInvencion] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NombreOperador] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ActividadNegocio] [text] COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NumeroSocios] [int] NULL,
[TotalAcciones] [int] NULL,
[EsNuevoRegistro] [bit] NOT NULL CONSTRAINT [DF_Registros_EsNuevoRegistro] DEFAULT ((0)),
[DireccionCalle] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DireccionNumero] [nvarchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DireccionCiudadId] [int] NULL,
[DireccionCiudad] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DireccionSectorId] [int] NULL,
[DireccionApartadoPostal] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DireccionTelefonoCasa] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DireccionTelefonoOficina] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DireccionExtension] [int] NULL,
[DireccionFax] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DireccionEmail] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DireccionSitioWeb] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NombreSolicitante] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CargoSolicitante] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GestorUsername] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FechaSolicitud] [datetime] NULL,
[EntidadActiva] [bit] NULL CONSTRAINT [DF_Registros_EntidadActiva] DEFAULT ((1)),
[EsRenovacion] [bit] NOT NULL CONSTRAINT [DF_Registros_EsModificacion] DEFAULT ((0)),
[TipoMonedaCapitalSocial] [int] NULL,
[TipoMonedaCapitalAutorizado] [int] NULL,
[TipoMonedaCapitalPagado] [int] NULL,
[TipoMonedaActivos] [int] NULL,
[TipoMonedaBienesRaices] [int] NULL
)
GO
ALTER TABLE [WebSRM].[Registros] ADD CONSTRAINT [PK_Registros] PRIMARY KEY CLUSTERED  ([RegistroId])
GO
