//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.Membership
{
    public partial class vw_aspnet_WebPartState_Paths
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    		public static string ApplicationId = @"ApplicationId";
    public static string PathId = @"PathId";
    public static string Path = @"Path";
    public static string LoweredPath = @"LoweredPath";
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual System.Guid ApplicationId
        {
            get;
            set;
        }
    
        public virtual System.Guid PathId
        {
            get;
            set;
        }
    
        public virtual string Path
        {
            get;
            set;
        }
    
        public virtual string LoweredPath
        {
            get;
            set;
        }

        #endregion

    }
}
