//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.CamaraComun
{
    public partial class Ciudades
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    			public static string CiudadId = @"CiudadId";	
    	public static string Nombre = @"Nombre";	
    	public static string PaisId = @"PaisId";	
    	public static string Orden = @"Orden";	
    	public static string FechaModificacion = @"FechaModificacion";	
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int CiudadId
        {
            get;
            set;
        }
    
        public virtual string Nombre
        {
            get;
            set;
        }
    
        public virtual Nullable<int> PaisId
        {
            get { return _paisId; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_paisId != value)
                    {
                        if (Paises != null && Paises.PaisId != value)
                        {
                            Paises = null;
                        }
                        _paisId = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _paisId;
    
        public virtual int Orden
        {
            get;
            set;
        }
    
        public virtual System.DateTime FechaModificacion
        {
            get;
            set;
        }
    
        public virtual System.Guid rowguid
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual Paises Paises
        {
            get { return _paises; }
            set
            {
                if (!ReferenceEquals(_paises, value))
                {
                    var previousValue = _paises;
                    _paises = value;
                    FixupPaises(previousValue);
                }
            }
        }
        private Paises _paises;
    
        public virtual ICollection<Sectores> Sectores
        {
            get
            {
                if (_sectores == null)
                {
                    var newCollection = new FixupCollection<Sectores>();
                    newCollection.CollectionChanged += FixupSectores;
                    _sectores = newCollection;
                }
                return _sectores;
            }
            set
            {
                if (!ReferenceEquals(_sectores, value))
                {
                    var previousValue = _sectores as FixupCollection<Sectores>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSectores;
                    }
                    _sectores = value;
                    var newValue = value as FixupCollection<Sectores>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSectores;
                    }
                }
            }
        }
        private ICollection<Sectores> _sectores;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupPaises(Paises previousValue)
        {
            if (previousValue != null && previousValue.Ciudades.Contains(this))
            {
                previousValue.Ciudades.Remove(this);
            }
    
            if (Paises != null)
            {
                if (!Paises.Ciudades.Contains(this))
                {
                    Paises.Ciudades.Add(this);
                }
                if (PaisId != Paises.PaisId)
                {
                    PaisId = Paises.PaisId;
                }
            }
            else if (!_settingFK)
            {
                PaisId = null;
            }
        }
    
        private void FixupSectores(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Sectores item in e.NewItems)
                {
                    item.Ciudades = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Sectores item in e.OldItems)
                {
                    if (ReferenceEquals(item.Ciudades, this))
                    {
                        item.Ciudades = null;
                    }
                }
            }
        }

        #endregion

    }
}
