//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CamaraComercio.WebServices.WebSrmWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FacturacionSRMSoap", Namespace="http://tempuri.org/")]
    public partial class FacturacionSRM : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GenerarNotaCreditoSRMOperationCompleted;
        
        private System.Threading.SendOrPostCallback AgregaPagosConNotasVigentesSRMOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidacionVigenciaNotaCreditoSRMOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FacturacionSRM() {
            this.Url = global::CamaraComercio.WebServices.Properties.Settings.Default.CamaraComercio_WebServices_WebSrmWS_FacturacionSRM;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GenerarNotaCreditoSRMCompletedEventHandler GenerarNotaCreditoSRMCompleted;
        
        /// <remarks/>
        public event AgregaPagosConNotasVigentesSRMCompletedEventHandler AgregaPagosConNotasVigentesSRMCompleted;
        
        /// <remarks/>
        public event ValidacionVigenciaNotaCreditoSRMCompletedEventHandler ValidacionVigenciaNotaCreditoSRMCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerarNotaCreditoSRM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TipoRespuestaNotaCredito GenerarNotaCreditoSRM(int transaccionId, string usuario, string camaraId) {
            object[] results = this.Invoke("GenerarNotaCreditoSRM", new object[] {
                        transaccionId,
                        usuario,
                        camaraId});
            return ((TipoRespuestaNotaCredito)(results[0]));
        }
        
        /// <remarks/>
        public void GenerarNotaCreditoSRMAsync(int transaccionId, string usuario, string camaraId) {
            this.GenerarNotaCreditoSRMAsync(transaccionId, usuario, camaraId, null);
        }
        
        /// <remarks/>
        public void GenerarNotaCreditoSRMAsync(int transaccionId, string usuario, string camaraId, object userState) {
            if ((this.GenerarNotaCreditoSRMOperationCompleted == null)) {
                this.GenerarNotaCreditoSRMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarNotaCreditoSRMOperationCompleted);
            }
            this.InvokeAsync("GenerarNotaCreditoSRM", new object[] {
                        transaccionId,
                        usuario,
                        camaraId}, this.GenerarNotaCreditoSRMOperationCompleted, userState);
        }
        
        private void OnGenerarNotaCreditoSRMOperationCompleted(object arg) {
            if ((this.GenerarNotaCreditoSRMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarNotaCreditoSRMCompleted(this, new GenerarNotaCreditoSRMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregaPagosConNotasVigentesSRM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FormasPagoViewModel AgregaPagosConNotasVigentesSRM(int transaccionId, string camaraId) {
            object[] results = this.Invoke("AgregaPagosConNotasVigentesSRM", new object[] {
                        transaccionId,
                        camaraId});
            return ((FormasPagoViewModel)(results[0]));
        }
        
        /// <remarks/>
        public void AgregaPagosConNotasVigentesSRMAsync(int transaccionId, string camaraId) {
            this.AgregaPagosConNotasVigentesSRMAsync(transaccionId, camaraId, null);
        }
        
        /// <remarks/>
        public void AgregaPagosConNotasVigentesSRMAsync(int transaccionId, string camaraId, object userState) {
            if ((this.AgregaPagosConNotasVigentesSRMOperationCompleted == null)) {
                this.AgregaPagosConNotasVigentesSRMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregaPagosConNotasVigentesSRMOperationCompleted);
            }
            this.InvokeAsync("AgregaPagosConNotasVigentesSRM", new object[] {
                        transaccionId,
                        camaraId}, this.AgregaPagosConNotasVigentesSRMOperationCompleted, userState);
        }
        
        private void OnAgregaPagosConNotasVigentesSRMOperationCompleted(object arg) {
            if ((this.AgregaPagosConNotasVigentesSRMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregaPagosConNotasVigentesSRMCompleted(this, new AgregaPagosConNotasVigentesSRMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidacionVigenciaNotaCreditoSRM", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VigenciaNotaCreditoViewModel ValidacionVigenciaNotaCreditoSRM(int transaccionId, string camaraId) {
            object[] results = this.Invoke("ValidacionVigenciaNotaCreditoSRM", new object[] {
                        transaccionId,
                        camaraId});
            return ((VigenciaNotaCreditoViewModel)(results[0]));
        }
        
        /// <remarks/>
        public void ValidacionVigenciaNotaCreditoSRMAsync(int transaccionId, string camaraId) {
            this.ValidacionVigenciaNotaCreditoSRMAsync(transaccionId, camaraId, null);
        }
        
        /// <remarks/>
        public void ValidacionVigenciaNotaCreditoSRMAsync(int transaccionId, string camaraId, object userState) {
            if ((this.ValidacionVigenciaNotaCreditoSRMOperationCompleted == null)) {
                this.ValidacionVigenciaNotaCreditoSRMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidacionVigenciaNotaCreditoSRMOperationCompleted);
            }
            this.InvokeAsync("ValidacionVigenciaNotaCreditoSRM", new object[] {
                        transaccionId,
                        camaraId}, this.ValidacionVigenciaNotaCreditoSRMOperationCompleted, userState);
        }
        
        private void OnValidacionVigenciaNotaCreditoSRMOperationCompleted(object arg) {
            if ((this.ValidacionVigenciaNotaCreditoSRMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidacionVigenciaNotaCreditoSRMCompleted(this, new ValidacionVigenciaNotaCreditoSRMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum TipoRespuestaNotaCredito {
        
        /// <remarks/>
        FacturaMontoCero,
        
        /// <remarks/>
        ErrorWebService,
        
        /// <remarks/>
        NotaCreditoCreada,
        
        /// <remarks/>
        EstadoInicial,
        
        /// <remarks/>
        NoPuedeGenerarGreditos,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FormasPagoViewModel {
        
        private string bancoDescripcionField;
        
        private System.Nullable<int> bancoIdField;
        
        private string confirmacionPagoTarjetaField;
        
        private decimal divisaField;
        
        private int facturaIdField;
        
        private System.DateTime fechaCuadreField;
        
        private string formaPagoField;
        
        private string formaPagoDescField;
        
        private int idField;
        
        private string notaField;
        
        private string noTarjetaField;
        
        private System.Nullable<int> numeroNotaCreditoField;
        
        private string referenciaField;
        
        private decimal tasaField;
        
        private decimal valorField;
        
        private decimal valorDevueltoField;
        
        private decimal valorEntregadoField;
        
        private string notaCreditoValidaField;
        
        private System.DateTime fechaCreacionNotaField;
        
        private string voucherField;
        
        /// <remarks/>
        public string BancoDescripcion {
            get {
                return this.bancoDescripcionField;
            }
            set {
                this.bancoDescripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> BancoId {
            get {
                return this.bancoIdField;
            }
            set {
                this.bancoIdField = value;
            }
        }
        
        /// <remarks/>
        public string ConfirmacionPagoTarjeta {
            get {
                return this.confirmacionPagoTarjetaField;
            }
            set {
                this.confirmacionPagoTarjetaField = value;
            }
        }
        
        /// <remarks/>
        public decimal Divisa {
            get {
                return this.divisaField;
            }
            set {
                this.divisaField = value;
            }
        }
        
        /// <remarks/>
        public int FacturaId {
            get {
                return this.facturaIdField;
            }
            set {
                this.facturaIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaCuadre {
            get {
                return this.fechaCuadreField;
            }
            set {
                this.fechaCuadreField = value;
            }
        }
        
        /// <remarks/>
        public string FormaPago {
            get {
                return this.formaPagoField;
            }
            set {
                this.formaPagoField = value;
            }
        }
        
        /// <remarks/>
        public string FormaPagoDesc {
            get {
                return this.formaPagoDescField;
            }
            set {
                this.formaPagoDescField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Nota {
            get {
                return this.notaField;
            }
            set {
                this.notaField = value;
            }
        }
        
        /// <remarks/>
        public string NoTarjeta {
            get {
                return this.noTarjetaField;
            }
            set {
                this.noTarjetaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> NumeroNotaCredito {
            get {
                return this.numeroNotaCreditoField;
            }
            set {
                this.numeroNotaCreditoField = value;
            }
        }
        
        /// <remarks/>
        public string Referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        public decimal Tasa {
            get {
                return this.tasaField;
            }
            set {
                this.tasaField = value;
            }
        }
        
        /// <remarks/>
        public decimal Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorDevuelto {
            get {
                return this.valorDevueltoField;
            }
            set {
                this.valorDevueltoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorEntregado {
            get {
                return this.valorEntregadoField;
            }
            set {
                this.valorEntregadoField = value;
            }
        }
        
        /// <remarks/>
        public string NotaCreditoValida {
            get {
                return this.notaCreditoValidaField;
            }
            set {
                this.notaCreditoValidaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaCreacionNota {
            get {
                return this.fechaCreacionNotaField;
            }
            set {
                this.fechaCreacionNotaField = value;
            }
        }
        
        /// <remarks/>
        public string Voucher {
            get {
                return this.voucherField;
            }
            set {
                this.voucherField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VigenciaNotaCreditoViewModel {
        
        private string notaCreditoValidaField;
        
        private System.DateTime fechaCreacionNotaField;
        
        private int diasTranscurridosField;
        
        private int idNotaCreditoField;
        
        /// <remarks/>
        public string NotaCreditoValida {
            get {
                return this.notaCreditoValidaField;
            }
            set {
                this.notaCreditoValidaField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime FechaCreacionNota {
            get {
                return this.fechaCreacionNotaField;
            }
            set {
                this.fechaCreacionNotaField = value;
            }
        }
        
        /// <remarks/>
        public int DiasTranscurridos {
            get {
                return this.diasTranscurridosField;
            }
            set {
                this.diasTranscurridosField = value;
            }
        }
        
        /// <remarks/>
        public int IdNotaCredito {
            get {
                return this.idNotaCreditoField;
            }
            set {
                this.idNotaCreditoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GenerarNotaCreditoSRMCompletedEventHandler(object sender, GenerarNotaCreditoSRMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarNotaCreditoSRMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarNotaCreditoSRMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TipoRespuestaNotaCredito Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TipoRespuestaNotaCredito)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AgregaPagosConNotasVigentesSRMCompletedEventHandler(object sender, AgregaPagosConNotasVigentesSRMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregaPagosConNotasVigentesSRMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregaPagosConNotasVigentesSRMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FormasPagoViewModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FormasPagoViewModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ValidacionVigenciaNotaCreditoSRMCompletedEventHandler(object sender, ValidacionVigenciaNotaCreditoSRMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidacionVigenciaNotaCreditoSRMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidacionVigenciaNotaCreditoSRMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VigenciaNotaCreditoViewModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VigenciaNotaCreditoViewModel)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591