//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.Membership
{
    public partial class CamaraSystems
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    		public static string SystemId = @"SystemId";
    public static string Description = @"Description";
    public static string Active = @"Active";
    public static string CreatedOn = @"CreatedOn";
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual System.Guid SystemId
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual bool Active
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedOn
        {
            get;
            set;
        }

        #endregion

    }
}
