using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using CamaraComercio.DataAccess.EF.CamaraComun;
using Telerik.Web.UI;

namespace CamaraComercio.Admin.admin
{
    public partial class admin_camaras : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }

        protected void RadGrid1_UpdateCommand(object source, Telerik.Web.UI.GridCommandEventArgs e)
        {
            GridEditableItem editItem = (GridEditableItem)e.Item;
            
            var id = ((TextBox)editItem["ID"].Controls[1]).Text.Trim();
            var nombre = ((TextBox)editItem["Nombre"].Controls[1]).Text.Trim();
            var gestionId= Convert.ToInt32(((TextBox)editItem["GestionID"].Controls[1]).Text.Trim());
            var RNC = ((TextBox)editItem["RNC"].Controls[1]).Text.Trim();
            var activa = ((CheckBox)editItem["Activa"].Controls[1]).Checked;
            var header = ((TextBox)editItem["HeaderImpresiones"].Controls[1]).Text.Trim();

            
            CamarasController.Update(id, nombre, gestionId, RNC, activa, header);         
            
          
        }

        protected void RadGrid1_NeedDataSource(object source, GridNeedDataSourceEventArgs e)
        {

        }

        protected void RadGrid1_DeleteCommand(object source, GridCommandEventArgs e)
        {
            //buscar el id
            var id = e.Item.OwnerTableView.DataKeyValues[e.Item.ItemIndex]["ID"];

            //llamar el metodo delete
            CamarasController.Delete(id.ToString());
        }

        protected void RadGrid1_ItemInserted(object source, GridInsertedEventArgs e)
        {

        }

        protected void RadGrid1_InsertCommand(object source, GridCommandEventArgs e)
        {
            GridEditableItem editItem = (GridEditableItem)e.Item;

            
            var id = ((TextBox)editItem["ID"].Controls[1]).Text.Trim();
            var nombre = ((TextBox)editItem["Nombre"].Controls[1]).Text.Trim();
            var gestionId = Convert.ToInt32(((TextBox)editItem["GestionID"].Controls[1]).Text.Trim());
            var RNC = ((TextBox)editItem["RNC"].Controls[1]).Text.Trim();
            var activa = ((CheckBox)editItem["Activa"].Controls[1]).Checked;
            var header = ((TextBox)editItem["HeaderImpresiones"].Controls[1]).Text.Trim();


            CamarasController.Insert(id, nombre, gestionId, RNC, activa, header);       
        }

        protected void RadGrid1_ItemDataBound(object sender, GridItemEventArgs e)
        {
            if (e.Item is GridDataItem)
            {
                GridDataItem item = (GridDataItem)e.Item;
                
                ((LinkButton)item["AutoGeneratedDeleteColumn"].Controls[0]).Text = "Borrar";
            }

            if (e.Item is GridPagerItem)
            {
                GridPagerItem pager = (GridPagerItem)e.Item;
                Label lbl = (Label)pager.FindControl("ChangePageSizeLabel");
                lbl.Visible = false;

                RadComboBox combo = (RadComboBox)pager.FindControl("PageSizeComboBox");
                combo.Visible = false;
            } 
        }
    }
}