//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CamaraComercio.DataAccess.EF.SRM
{
    public partial class LibroDigital
    {
        #region Property Metadata
    	
    	public struct PropColumns
    	{
    		public static string LibroId = @"LibroId";
    public static string NumeroLibro = @"NumeroLibro";
    public static string Folio = @"Folio";
    public static string NumeroDocumento = @"NumeroDocumento";
    public static string Sufijo = @"Sufijo";
     
    	}
        #endregion

        #region Primitive Properties
    
        public virtual int LibroId
        {
            get;
            set;
        }
    
        public virtual int NumeroLibro
        {
            get;
            set;
        }
    
        public virtual int Folio
        {
            get;
            set;
        }
    
        public virtual int NumeroDocumento
        {
            get;
            set;
        }
    
        public virtual string Sufijo
        {
            get;
            set;
        }

        #endregion

    }
}
